site/src/main/java/org/sibza/model/user/Phone.java
package org.sibza.model.user;

import org.sibza.model.Model;
import org.sibza.utils.DBase;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by timur on 31.05.15.
 *
 * Модель номера телефона
 */
public class Phone extends Model {

    private String phone;

    public Phone(int id, String phone) {

        super(id);
        this.phone = phone;
    }

    public String getPhone() {

        return phone;
    }

    public void setPhone(String phone) {

        this.phone = phone;
    }

    @Override
    public String toString() {

        return phone;
    }
}

site/src/main/java/org/sibza/model/user/Role.java
package org.sibza.model.user;

import org.sibza.model.Model;
import org.sibza.utils.DBase;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;

/**
 * Created by timur on 09.05.15.
 *
 * Роль пользователя
 */
public class Role extends Model {

    public static final int ROLE_ADMIN = 1;
    public static final int ROLE_EDITOR = 2;
    public static final int ROLE_USER = 3;

    public Role(int id) {

        super(id);
    }

    public Role(int id, String name) {

        super(id, name);
    }
}

site/src/main/java/org/sibza/model/user/SocialNetwork.java
package org.sibza.model.user;

import org.sibza.model.Model;

/**
 * Created by Тимур on 08.10.2015.
 *
 * Модель ссылки на аккаунт пользователя в социальной сети
 */
public class SocialNetwork extends Model {

    private SocialNetworkType type;
    private String account;

    public SocialNetwork(int id, SocialNetworkType type, String account) {

        super(id);
        this.type = type;

        if (account.trim().length() == 0) {
            this.account = null;
        } else {
            this.account = account;
        }
    }

    public SocialNetworkType getType() {

        return type;
    }

    public void setType(SocialNetworkType type) {

        this.type = type;
    }

    public String getAccount() {

        return account;
    }

    public void setAccount(String account) {

        if (account != null && account.trim().length() == 0) {
            this.account = null;
        } else {
            this.account = account;
        }
    }

    public String getAccountUrl() {

        return type.getAccountUrl() + account;
    }

    @Override
    public String toString() {

        return account;
    }
}

site/src/main/java/org/sibza/model/user/SocialNetworkType.java
package org.sibza.model.user;

import org.sibza.model.Model;

/**
 * Created by Тимур on 08.10.2015.
 *
 * Модель типа социальной сети
 */
public class SocialNetworkType extends Model {

    private String accountUrl;
    private String color;
    private String icon;

    public SocialNetworkType(int id) {

        super(id);
    }

    public SocialNetworkType(int id, String name, String accountUrl, String color, String icon) {

        super(id, name);
        this.accountUrl = accountUrl;
        this.color = color;
        this.icon = icon;
    }

    public String getAccountUrl() {

        return accountUrl;
    }

    public void setAccountUrl(String accountUrl) {

        this.accountUrl = accountUrl;
    }

    public String getColor() {

        return color;
    }

    public void setColor(String color) {

        this.color = color;
    }

    public String getIcon() {

        return icon;
    }

    public void setIcon(String icon) {

        this.icon = icon;
    }
}

site/src/main/java/org/sibza/model/user/User.java
package org.sibza.model.user;

import org.sibza.model.Model;
import org.sibza.cache.Roles;
import org.sibza.model.post.Post;
import org.sibza.model.post.dao.PostDAOImpl;
import org.sibza.model.user.dao.FriendDAOImpl;
import org.sibza.model.user.dao.RoleDAOImpl;
import org.sibza.model.user.dao.SocialNetworkDAOImpl;
import org.sibza.utils.DBase;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Created by timur on 09.05.15.
 *
 * Модель пользователя
 */
public class User extends Model {

    private String fullName;
    private String email;
    private String nick;
    private UserInfo info;
    private String confirmCode;
    private boolean confirmed;
    private List<Role> roles;
    private List<SocialNetwork> socialNetworks;
    private List<Post> posts;
    private List<User> friends;
    private boolean hold;

    public User() {

        super();
    }

    public User(int id) {

        super(id);
    }

    public User(int id, String email) {

        super(id);
        this.email = email;
    }

    @Override
    public void setName(String name) {

        if (name != null && name.trim().length() == 0) {
            this.name = null;
        } else {
            this.name = name;
        }

        generateFullName();
    }

    public String getFullName() {

        return fullName;
    }

    public String getEmail() {

        return email;
    }

    public void setEmail(String email) {

        this.email = email;

        generateFullName();
    }

    public String getNick() {

        return nick;
    }

    public void setNick(String nick) {

        this.nick = nick != null ? nick.trim() : null;
    }

    public UserInfo getInfo() {

        if (info == null) {
            info = new UserInfo();
        }

        return info;
    }

    public String getConfirmCode() {

        return confirmCode;
    }

    public void setConfirmCode(String confirmCode) {

        this.confirmCode = confirmCode;
    }

    public boolean isConfirmed() {

        return confirmed;
    }

    public void setConfirmed(boolean confirmed) {

        this.confirmed = confirmed;
    }

    public List<Role> getRoles() {

        if (roles == null) {
            loadRoles();
        }

        return roles;
    }

    private void loadRoles() {

        if (roles != null) {
            roles.clear();
        }

        roles = new RoleDAOImpl().list(this);
    }

    public List<SocialNetwork> getSocialNetworks() {

        return socialNetworks;
    }

    public void loadSocialNetwords() {

        if (socialNetworks != null) {
            socialNetworks.clear();
        }

        socialNetworks = new SocialNetworkDAOImpl().list(this);
    }

    public SocialNetwork getSocialNetwork(int socialTypeId) {

        if (socialNetworks == null) {
            loadSocialNetwords();
        }

        if (socialNetworks != null) {
            for (SocialNetwork social : socialNetworks) {
                if (social.getType().getId() == socialTypeId) {
                    return social;
                }
            }
        }

        return null;
    }

    public String getSocialNetworkAccount(int socialTypeId) {

        SocialNetwork social = getSocialNetwork(socialTypeId);
        if (social != null) {
            return social.getAccount();
        }

        return "";
    }

    public List<Post> getPosts() {

        return posts;
    }

    public void loadPosts() {

        if (posts != null) {
            posts.clear();
        }

        posts = new PostDAOImpl().list(this);
    }

    public List<User> getFriends() {

        return friends;
    }

    public void loadFriends() {

        loadFriends(0, Integer.MAX_VALUE);
    }

    public void loadFriends(int offset, int count) {

        if (friends != null) {
            friends.clear();
        }

        friends = new FriendDAOImpl().list(this, offset, count);
    }

    public void clearFriends() {

        if (friends != null) {
            friends.clear();
        }

        friends = null;
    }

    public boolean hisFriend(User friend) {

        if (friends == null) {
            loadFriends();
        }

        if (friends == null || friends.size() == 0) {
            return false;
        }

        for (User user : friends) {
            if (user.getId() == friend.getId()) {
                return true;
            }
        }

        return false;
    }

    public String getProfileUrl() {

        if (nick != null && nick.length() != 0) {
            return nick;
        }

        return "id" + id;
    }

    public String getAvatarUrl() {

        final String AVATAR_BASE_URL = String.format("/users/profile/%d/avatar", id);

        if (info.getAvatar() != null) {
            return String.format("%s/%d/%s", AVATAR_BASE_URL, info.getAvatar().getId(), info.getAvatar().getFileName());
        } else {
            return info.getDefaultAvatar().toString();
        }
    }

    public boolean isHold() {

        return hold;
    }

    public void setHold(boolean hold) {

        this.hold = hold;
    }

    @Override
    public String toString() {

        return fullName;
    }

    /**
     * Генерирует новый код подтверждения
     *
     * @return
     */
    public static String genConfirmCode() {

        return UUID.randomUUID().toString().replaceAll("-", "");
    }

    private void generateFullName() {

        if (name != null) {
            fullName = name;
        } else if (nick != null) {
            fullName = nick;
        } else {
            fullName = email;
        }
    }
}

site/src/main/java/org/sibza/model/user/UserInfo.java
package org.sibza.model.user;

import org.sibza.model.Model;
import org.sibza.model.avatar.DefaultAvatar;
import org.sibza.model.resource.Resource;

import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by timur on 09.10.15.
 *
 * Дополнительная инфорация по пользователю
 */
public class UserInfo extends Model {

    private int gender;
    private Date birthday;
    private String about;
    private String address;
    private String phone;
    private String site;
    private DefaultAvatar defaultAvatar;
    private Resource avatar;

    public int getGender() {

        return gender;
    }

    public void setGender(int gender) {

        this.gender = gender;
    }

    public Date getBirthday() {

        return birthday;
    }

    public String getBirthdayStr() {

        if (birthday == null) {
            return null;
        }

        return new SimpleDateFormat("dd.MM.yyyy").format(birthday);
    }

    public void setBirthday(Date birthday) {

        this.birthday = birthday;
    }

    public String getAbout() {

        return about;
    }

    public void setAbout(String about) {

        if (about != null && about.trim().length() == 0) {
            this.about = null;
        } else {
            this.about = about;
        }
    }

    public String getAddress() {

        return address;
    }

    public void setAddress(String address) {

        if (address != null && address.trim().length() == 0) {
            this.address = null;
        } else {
            this.address = address;
        }
    }

    public String getPhone() {

        return phone;
    }

    public void setPhone(String phone) {

        if (phone != null && phone.trim().length() == 0) {
            this.phone = null;
        } else {
            this.phone = phone;
        }
    }

    public String getSite() {

        return site;
    }

    public void setSite(String site) {

        if (site != null && site.trim().length() == 0) {
            this.site = null;
        } else {
            this.site = site;
        }
    }

    public DefaultAvatar getDefaultAvatar() {

        return defaultAvatar;
    }

    public void setDefaultAvatar(DefaultAvatar defaultAvatar) {

        this.defaultAvatar = defaultAvatar;
    }

    public Resource getAvatar() {

        return avatar;
    }

    public void setAvatar(Resource avatar) {

        this.avatar = avatar;
    }
}

site/src/main/java/org/sibza/model/user/UserReg.java
package org.sibza.model.user;

/**
 * Created by timur on 10.10.15.
 *
 * Данные по регистрации пользователя
 */
public class UserReg {

    private String email;
    private String name;
    private String password1;
    private String password2;

    public UserReg(String email, String name, String password1, String password2) {

        this.email = email != null ? email.trim() : null;
        this.name = name != null ? name.trim() : null;
        this.password1 = password1 != null ? password1.trim() : null;
        this.password2 = password2 != null ? password2.trim() : null;
    }

    public String getEmail() {

        return email;
    }

    public void setEmail(String email) {

        this.email = email;
    }

    public String getName() {

        return name;
    }

    public void setName(String name) {

        this.name = name;
    }

    public String getPassword1() {

        return password1;
    }

    public void setPassword1(String password1) {

        this.password1 = password1;
    }

    public String getPassword2() {

        return password2;
    }

    public void setPassword2(String password2) {

        this.password2 = password2;
    }
}

site/src/main/java/org/sibza/model/user/dao/FriendDAOImpl.java
package org.sibza.model.user.dao;

import org.sibza.cache.DefaultAvatars;
import org.sibza.model.ModelDAOImpl;
import org.sibza.model.user.User;
import org.sibza.model.user.dao.interfaces.FriendDAO;
import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * Created by timur on 07.03.16.
 *
 * Реализация интерфейса по работе со списком друзей пользователя
 */
public class FriendDAOImpl extends ModelDAOImpl implements FriendDAO {

    private static final String QUERY_LIST = "{ call friends_list(?,?,?) }";
    private static final String QUERY_SAVE = "{ call friends_save(?,?) }";
    private static final String QUERY_DELETE = "{ call friends_delete(?,?) }";

    @Override
    public List<User> list(User user, int offset, int count) {

        final DefaultAvatars defaultAvatars = DefaultAvatars.getInstance();

        List<User> list = jdbcTemplate.query(QUERY_LIST, new Object[] { user.getId(), offset, count },
                new RowMapper<User>() {

                    @Override
                    public User mapRow(ResultSet resultSet, int i) throws SQLException {

                        User user = new UserDAOImpl().load(resultSet);
                        user.getInfo().setDefaultAvatar(defaultAvatars.get(user.getInfo().getDefaultAvatar().getId()));

                        return user;
                    }
                });


        return list;
    }

    @Override
    public boolean save(User user, User friend) {

        return jdbcTemplate.update(QUERY_SAVE, new Object[] { user.getId(), friend.getId() }) != 0;
    }

    @Override
    public boolean delete(User user, User friend) {

        return jdbcTemplate.update(QUERY_DELETE, new Object[] { user.getId(), friend.getId() }) != 0;
    }
}

site/src/main/java/org/sibza/model/user/dao/PhoneDAOImpl.java
package org.sibza.model.user.dao;

import org.sibza.model.ModelDAOImpl;
import org.sibza.model.user.Phone;
import org.sibza.model.user.dao.interfaces.PhoneDAO;
import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * Created by timur on 24.09.15.
 *
 * Реализация интерфейса для работы с номерами телефонов
 */
public class PhoneDAOImpl extends ModelDAOImpl implements PhoneDAO {

    private static final String QUERY_LIST = "{ call phones_list() }";

    @Override
    public List<Phone> list() {

        List<Phone> phones = jdbcTemplate.query(QUERY_LIST, new RowMapper<Phone>() {

            @Override
            public Phone mapRow(ResultSet resultSet, int i) throws SQLException {

                return load(resultSet);
            }
        });

        return phones;
    }

    private Phone load(ResultSet rs) throws SQLException {

        return new Phone(rs.getInt("id"), rs.getString("phone"));
    }
}

site/src/main/java/org/sibza/model/user/dao/RoleDAOImpl.java
package org.sibza.model.user.dao;

import org.sibza.model.ModelDAOImpl;
import org.sibza.model.user.Role;
import org.sibza.model.user.User;
import org.sibza.model.user.dao.interfaces.RoleDAO;
import org.springframework.jdbc.core.RowMapper;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

/**
 * Created by timur on 24.09.15.
 *
 * Реализация интерфейса для работы с ролями пользователей
 */
public class RoleDAOImpl extends ModelDAOImpl implements RoleDAO {

    private static final String QUERY_LIST = "{ call roles_list() }";
    private static final String QUERY_LIST_BY_USER = "{ call users_roles_list_by_user(?) }";

    @Override
    public List<Role> list() {

        List<Role> roles = jdbcTemplate.query(QUERY_LIST, new RowMapper<Role>() {

            @Override
            public Role mapRow(ResultSet resultSet, int i) throws SQLException {

                return load(resultSet);
            }
        });

        return roles;
    }

    @Override
    public List<Role> list(User user) {

        List<Role> roles = jdbcTemplate.query(QUERY_LIST_BY_USER, new RowMapper<Role>() {

            @Override
            public Role mapRow(ResultSet resultSet, int i) throws SQLException {

                return load(resultSet);
            }
        }, user.getId());

        return roles;
    }

    private Role load(ResultSet rs) throws SQLException {

        return new Role(rs.getInt("id"), rs.getString("name"));
    }
}

site/src/main/webapp/WEB-INF/views/material/user/edit.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<div class="tab-base">

    <!--Nav Tabs-->
    <ul class="nav nav-tabs">
        <li class="active">
            <a data-toggle="tab" href="#main-tab">${t.g("Основное")}</a>
        </li>
        <li>
            <a data-toggle="tab" href="#contact-tab">${t.g("Контакты")}</a>
        </li>
    </ul>

    <!--Tabs Content-->
    <div class="tab-content">
        <div id="main-tab" class="tab-pane fade active in">
            <form method="post" action="/users/profile/edit/main">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="nick">${t.g("Ник")}</label>
                            <input class="form-control" type="text" id="nick" name="nick"
                                   value="<c:if test="${user.nick != null}">${user.nick}</c:if>"
                                   placeholder="${t.g("Введите свой ник")}"/>
                            <small class="help-block">${t.g("Используется для формирования ссылки на профиль. Должен быть уникальным.")}</small>
                        </div>
                        <div class="form-group">
                            <label for="name">${t.g("Имя")}</label>
                            <input class="form-control" type="text" id="name" name="name"
                                   value="<c:if test="${user.name != null}">${user.name}</c:if>"
                                   placeholder="${t.g("Введите свое имя")}"/>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label class="col-md-3 control-label">${t.g("Пол")}</label>

                                    <div class="col-md-9">
                                        <label class="form-radio form-normal">
                                            <input type="radio" name="gender" value="1"
                                                    <c:if test="${user.info.gender == 1}">checked</c:if> /> ${t.g("Мужчина")}
                                        </label><br/>
                                        <label class="form-radio form-normal">
                                            <input type="radio" name="gender" value="2"
                                                   <c:if test="${user.info.gender == 2}">checked</c:if> /> ${t.g("Женщина")}
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="birthday">${t.g("Дата рождения")}</label>

                            <div class="input-group date">
                                <input class="form-control" type="text" id="birthday" name="birthday"
                                       value="<c:if test="${user.info.birthdayStr != null}">${user.info.birthdayStr}</c:if>" />
                                <span class="input-group-addon"><i class="fa fa-calendar fa-lg"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="about">${t.g("Обо мне")}</label>
                            <textarea class="form-control" rows="8" id="about" name="about"
                                      placeholder="${t.g("Напишите что-нибудь о себе")}"><c:if test="${user.info.about != null}">${user.info.about}</c:if></textarea>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-info" type="submit">${t.g("Сохранить")}</button>
                    <a class="btn btn-success" href="/users/${user.profileUrl}">${t.g("Вернуться")}</a>
                </div>
            </form>
            <hr/>

            <h3>${t.g("Смена пароля")}</h3>

            <form id="change-password-form" method="post" action="/users/profile/edit/password">
                <div class="form-group">
                    <label for="password_old">${t.g("Старый пароль")}</label>
                    <input class="form-control" type="password" id="password_old" name="password_old"
                           placeholder="${t.g("Введите текущий пароль")}"/>
                </div>
                <div class="form-group">
                    <label for="password1">${t.g("Новый пароль")}</label>
                    <input class="form-control" type="password" id="password1" name="password1"
                           placeholder="${t.g("Введите новый пароль")}"/>
                </div>
                <div class="form-group">
                    <label for="password2">${t.g("Новый пароль")}</label>
                    <input class="form-control" type="password" id="password2" name="password2"
                           placeholder="${t.g("Повторите новый пароль")}"/>
                </div>
                <div class="form-group">
                    <button class="btn btn-info" type="submit">${t.g("Сменить")}</button>
                    <a class="btn btn-success" href="/users/${user.profileUrl}">${t.g("Вернуться")}</a>
                </div>
            </form>
        </div>
        <div id="contact-tab" class="tab-pane fade">
            <form id="contact-form" method="post" action="/users/profile/edit/contact">
                <div class="form-group">
                    <label for="phone">${t.g("Мобильный номер")}</label>
                    <input class="form-control" type="text" id="phone" name="phone"
                           value="<c:if test="${user.info.phone != null}">${user.info.phone}</c:if>"
                           placeholder="${t.g("Введите номер мобильного телефона")}" />
                </div>
                <div class="form-group">
                    <label for="address">${t.g("Адрес")}</label>
                    <input class="form-control" type="text" id="address" name="address"
                           value="<c:if test="${user.info.address != null}">${user.info.address}</c:if>"
                           placeholder="${t.g("Введите свою страну и город")}" />
                </div>
                <div class="form-group">
                    <label for="site">${t.g("Сайт")}</label>
                    <input class="form-control" type="text" id="site" name="site"
                           value="<c:if test="${user.info.site != null}">${user.info.site}</c:if>"
                           placeholder="${t.g("Введите свой сайт (с http://)")}" />
                </div>
                <hr />

                <h3>${t.g("Социальные сети")}</h3>
                <c:forEach items="${socials}" var="social">
                    <div class="form-group">
                        <label for="social-${social.id}">${social.name}</label>
                        <input class="form-control" type="text" id="social-${social.id}" name="social-${social.id}"
                               value="${user.getSocialNetworkAccount(social.id)}" data-id="${social.id}"
                               placeholder="${social.name}" />
                        <input type="hidden" id="social-hidden-${social.id}"  name="social"
                               value="${social.id}###${user.getSocialNetworkAccount(social.id)}" />
                    </div>
                </c:forEach>

                <div class="form-group">
                    <button class="btn btn-info" id="contact-form-submit">${t.g("Сохранить")}</button>
                    <a class="btn btn-success" href="/users/${user.profileUrl}">${t.g("Вернуться")}</a>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        // добавляем плагин для выбора даты
        $('.date').datepicker({
            format: "dd.mm.yyyy",
            todayBtn: "linked",
            autoclose: true,
            todayHighlight: true
        });

        $('#contact-form-submit').click(function() {
            <c:forEach items="${socials}" var="social">
                $('#social-hidden-${social.id}').val('${social.id}###' + $('#social-${social.id}').val());
            </c:forEach>
            $('#contact-form').submit();
        });

        $('#change-password-form').bootstrapValidator({
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'fa fa-check-circle fa-lg text-success',
                invalid: 'fa fa-times-circle fa-lg',
                validating: 'fa fa-refresh'
            },
            fields: {
                password_old: {
                    validators: {
                        notEmpty: {
                            message: 'The password is required and can\'t be empty'
                        }
                    }
                },
                password1: {
                    validators: {
                        notEmpty: {
                            message: 'The password is required and can\'t be empty'
                        },
                        identical: {
                            field: 'password2',
                            message: 'The password and its confirm are not the same'
                        }
                    }
                },
                password2: {
                    validators: {
                        notEmpty: {
                            message: 'The confirm password is required and can\'t be empty'
                        },
                        identical: {
                            field: 'password1',
                            message: 'The password and its confirm are not the same'
                        }
                    }
                }
            }
        }).on('success.field.bv', function(e, data) {});
    });
</script>

site/src/main/webapp/WEB-INF/views/material/user/recover.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>

<form id="recover-form" method="post" action="/security/recover">
    <div class="row">
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div class="panel">
                <div class="panel-body">
                    <div class="form-group">
                        <label for="password1">${t.g("Новый пароль")}</label>
                        <input class="form-control" type="password" id="password1" name="password1"
                               placeholder="${t.g("Введите новый пароль")}"/>
                    </div>
                    <div class="form-group">
                        <label for="password2">${t.g("Новый пароль")}</label>
                        <input class="form-control" type="password" id="password2" name="password2"
                               placeholder="${t.g("Повторите новый пароль")}"/>
                    </div>
                </div>
                <div class="panel-footer text-right">
                    <button class="btn btn-info" type="submit">${t.g("Сменить")}</button>
                </div>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function() {
        $('#recover-form').bootstrapValidator({
            message: 'This value is not valid',
            feedbackIcons: {
                valid: 'fa fa-check-circle fa-lg text-success',
                invalid: 'fa fa-times-circle fa-lg',
                validating: 'fa fa-refresh'
            },
            fields: {
                password1: {
                    validators: {
                        notEmpty: {
                            message: 'The password is required and can\'t be empty'
                        },
                        identical: {
                            field: 'password2',
                            message: 'The password and its confirm are not the same'
                        }
                    }
                },
                password2: {
                    validators: {
                        notEmpty: {
                            message: 'The confirm password is required and can\'t be empty'
                        },
                        identical: {
                            field: 'password1',
                            message: 'The password and its confirm are not the same'
                        }
                    }
                }
            }
        }).on('success.field.bv', function(e, data) {});
    });
</script>